name: fastlane_cli
description: CLI plugin that bootstraps Fastlane, Firebase App Distribution, and GitHub Actions for Flutter projects.
version: 0.1.12
homepage: https://github.com/Mahmoud-t0lba/fastlane_cli
repository: https://github.com/Mahmoud-t0lba/fastlane_cli
issue_tracker: https://github.com/Mahmoud-t0lba/fastlane_cli/issues
topics:
  - fastlane
  - firebase
  - github-actions
  - ci

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.7.0
  http: ^1.5.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3

executables:
  fastlane_cli: fastlane_cli
  flc: fastlane_cli
